create or replace schema sales;


create or replace table sales.dim_customers (
    CUSTOMER_ID INTEGER PRIMARY KEY,
    CUST_FIRST_NAME VARCHAR,
    CUST_LAST_NAME VARCHAR,
    STREET_ADDRESS VARCHAR,
    POSTAL_CODE INTEGER,
    CITY VARCHAR,
    STATE_PROVINCE VARCHAR,
    COUNTRY_ID VARCHAR,
    COUNTRY_NAME VARCHAR,
    REGION_ID INTEGER,
    NLS_LANGUAGE VARCHAR,
    NLS_TERRITORY VARCHAR,
    CREDIT_LIMIT INTEGER,
    CUST_EMAIL VARCHAR,
    PRIMARY_PHONE_NUMBER VARCHAR,
    PHONE_NUMBER_2 VARCHAR,
    ACCOUNT_MGR_ID INTEGER,
    LOCATION_GTYPE INTEGER,
    LOCATION_SRID INTEGER,
    LOCATION_X FLOAT,
    LOCATION_Y FLOAT
)
;

create or replace table sales.dim_promotions (
    PROMO_ID INTEGER PRIMARY KEY,
    PROMO_NAME VARCHAR
)
;

create or replace table sales.dim_products (
    PRODUCT_ID INTEGER PRIMARY KEY,
    PRODUCT_NAME VARCHAR,
    LANGUAGE_ID INTEGER,
    MIN_PRICE FLOAT,
    LIST_PRICE FLOAT,
    PRODUCT_STATUS VARCHAR,
    SUPPLIER_ID INTEGER,
    WARRANTY_PERIOD INTEGER,
    WEIGHT_CLASS INTEGER,
    PRODUCT_DESCRIPTION VARCHAR,
    CATEGORY_ID INTEGER,
    CATALOG_URL VARCHAR,
    SUB_CATEGORY_NAME VARCHAR,
    SUB_CATEGORY_DESCRIPTION VARCHAR,
    PARENT_CATEGORY_ID INTEGER,
    CATEGORY_NAME VARCHAR
);

